/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package umariana.cupi2.esports.interfaz;

/**
 *
 * @author Usuario
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        eSportsTitulo = new javax.swing.JLabel();
        fondoTitulo = new javax.swing.JPanel();
        fondoRegistroPartidas = new javax.swing.JPanel();
        registroPartidasTitulo = new javax.swing.JLabel();
        fondoRegistroJugadores = new javax.swing.JPanel();
        registroJugadoresTitulo = new javax.swing.JLabel();
        nombreRegistro = new javax.swing.JTextField();
        nombreTitulo = new javax.swing.JLabel();
        nicknameTitulo = new javax.swing.JLabel();
        nicknameRegistro = new javax.swing.JTextField();
        correoTitulo = new javax.swing.JLabel();
        correoRegistro = new javax.swing.JTextField();
        equipoTitulo = new javax.swing.JLabel();
        equipoRegistro = new javax.swing.JComboBox<>();
        registroJugadorBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        background.setBackground(new java.awt.Color(0, 0, 51));
        background.setLayout(null);

        eSportsTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 48)); // NOI18N
        eSportsTitulo.setForeground(new java.awt.Color(255, 255, 255));
        eSportsTitulo.setText("ESports");
        background.add(eSportsTitulo);
        eSportsTitulo.setBounds(420, 40, 190, 60);

        fondoTitulo.setBackground(new java.awt.Color(51, 0, 102));
        fondoTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout fondoTituloLayout = new javax.swing.GroupLayout(fondoTitulo);
        fondoTitulo.setLayout(fondoTituloLayout);
        fondoTituloLayout.setHorizontalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );
        fondoTituloLayout.setVerticalGroup(
            fondoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        background.add(fondoTitulo);
        fondoTitulo.setBounds(60, 20, 910, 90);

        fondoRegistroPartidas.setBackground(new java.awt.Color(30, 78, 78));

        registroPartidasTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        registroPartidasTitulo.setForeground(new java.awt.Color(255, 255, 255));
        registroPartidasTitulo.setText("Registro de partidas");

        javax.swing.GroupLayout fondoRegistroPartidasLayout = new javax.swing.GroupLayout(fondoRegistroPartidas);
        fondoRegistroPartidas.setLayout(fondoRegistroPartidasLayout);
        fondoRegistroPartidasLayout.setHorizontalGroup(
            fondoRegistroPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegistroPartidasLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(registroPartidasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        fondoRegistroPartidasLayout.setVerticalGroup(
            fondoRegistroPartidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoRegistroPartidasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(registroPartidasTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
        );

        background.add(fondoRegistroPartidas);
        fondoRegistroPartidas.setBounds(520, 130, 460, 580);

        fondoRegistroJugadores.setBackground(new java.awt.Color(107, 64, 133));

        registroJugadoresTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 36)); // NOI18N
        registroJugadoresTitulo.setForeground(new java.awt.Color(255, 255, 255));
        registroJugadoresTitulo.setText("Registro de jugadores");

        nombreRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreRegistroActionPerformed(evt);
            }
        });

        nombreTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        nombreTitulo.setForeground(new java.awt.Color(255, 255, 255));
        nombreTitulo.setText("Nombre completo");

        nicknameTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        nicknameTitulo.setForeground(new java.awt.Color(255, 255, 255));
        nicknameTitulo.setText("Nickname");

        nicknameRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameRegistroActionPerformed(evt);
            }
        });

        correoTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        correoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        correoTitulo.setText("Correo electronico");

        correoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoRegistroActionPerformed(evt);
            }
        });

        equipoTitulo.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        equipoTitulo.setForeground(new java.awt.Color(255, 255, 255));
        equipoTitulo.setText("Equipo en el que te vas a registrar");

        equipoRegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        registroJugadorBoton.setBackground(new java.awt.Color(51, 0, 51));
        registroJugadorBoton.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        registroJugadorBoton.setForeground(new java.awt.Color(255, 255, 255));
        registroJugadorBoton.setText("Registrar");
        registroJugadorBoton.setBorder(null);
        registroJugadorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroJugadorBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoRegistroJugadoresLayout = new javax.swing.GroupLayout(fondoRegistroJugadores);
        fondoRegistroJugadores.setLayout(fondoRegistroJugadoresLayout);
        fondoRegistroJugadoresLayout.setHorizontalGroup(
            fondoRegistroJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoRegistroJugadoresLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(registroJugadoresTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(fondoRegistroJugadoresLayout.createSequentialGroup()
                .addGroup(fondoRegistroJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoRegistroJugadoresLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(fondoRegistroJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(equipoRegistro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(equipoTitulo)
                            .addComponent(correoTitulo)
                            .addComponent(correoRegistro)
                            .addComponent(nicknameTitulo)
                            .addComponent(nicknameRegistro)
                            .addComponent(nombreTitulo)
                            .addComponent(nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fondoRegistroJugadoresLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(registroJugadorBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoRegistroJugadoresLayout.setVerticalGroup(
            fondoRegistroJugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoRegistroJugadoresLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(registroJugadoresTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(nombreTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nicknameTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nicknameRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(correoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(equipoTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(registroJugadorBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        background.add(fondoRegistroJugadores);
        fondoRegistroJugadores.setBounds(40, 130, 440, 580);

        getContentPane().add(background);
        background.setBounds(0, 0, 1020, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreRegistroActionPerformed

    private void nicknameRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameRegistroActionPerformed

    private void correoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoRegistroActionPerformed

    private void registroJugadorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroJugadorBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registroJugadorBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JTextField correoRegistro;
    private javax.swing.JLabel correoTitulo;
    private javax.swing.JLabel eSportsTitulo;
    private javax.swing.JComboBox<String> equipoRegistro;
    private javax.swing.JLabel equipoTitulo;
    private javax.swing.JPanel fondoRegistroJugadores;
    private javax.swing.JPanel fondoRegistroPartidas;
    private javax.swing.JPanel fondoTitulo;
    private javax.swing.JTextField nicknameRegistro;
    private javax.swing.JLabel nicknameTitulo;
    private javax.swing.JTextField nombreRegistro;
    private javax.swing.JLabel nombreTitulo;
    private javax.swing.JButton registroJugadorBoton;
    private javax.swing.JLabel registroJugadoresTitulo;
    private javax.swing.JLabel registroPartidasTitulo;
    // End of variables declaration//GEN-END:variables
}
