/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package umariana.cupi2.esports.interfaz;

import umariana.cupi2.esports.mundo.Esports;
import umariana.cupi2.esports.mundo.Equipo;

/**
 *
 * @author Usuario
 */
public class PanelRegistroPartidas extends javax.swing.JPanel {
private InterfazEsports ventana;
private Esports esports;
    /**
     * Creates new form PanelRegistroPartidas
     */
public PanelRegistroPartidas(InterfazEsports ventana, Esports modelo) {
    this.ventana = ventana;
    this.esports = modelo;
    initComponents();
    inicializarComboBoxes();
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            registrarPartidaActionPerformed(evt);
        }
    });
}

private void inicializarComboBoxes() {
    equipo.removeAllItems();
    rival.removeAllItems();
    equipo2.removeAllItems();
    rival2.removeAllItems();

    for (Equipo eq : esports.getEquipos()) {
        equipo.addItem(eq.getNombre());
        rival.addItem(eq.getNombre());
        equipo2.addItem(eq.getNombre());
        rival2.addItem(eq.getNombre());
    }
}

private void registrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {
    ventana.registrarPartida();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        backgroundTittle = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        team1Background1 = new javax.swing.JPanel();
        equipoTittle = new javax.swing.JLabel();
        equipo = new javax.swing.JComboBox<>();
        fecha = new javax.swing.JTextField();
        rivalTittle = new javax.swing.JLabel();
        rival = new javax.swing.JComboBox<>();
        marcador = new javax.swing.JTextField();
        kills = new javax.swing.JTextField();
        deaths = new javax.swing.JTextField();
        assists = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        team2Background = new javax.swing.JPanel();
        equipo2Tittle = new javax.swing.JLabel();
        equipo2 = new javax.swing.JComboBox<>();
        fecha2 = new javax.swing.JTextField();
        rival2Tittle = new javax.swing.JLabel();
        rival2 = new javax.swing.JComboBox<>();
        marcador2 = new javax.swing.JTextField();
        kills2 = new javax.swing.JTextField();
        deaths2 = new javax.swing.JTextField();
        assists2 = new javax.swing.JTextField();
        team1 = new javax.swing.JLabel();
        team2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(25, 13, 25));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(null);

        backgroundTittle.setBackground(new java.awt.Color(65, 35, 65));

        tittle.setFont(new java.awt.Font("Top Show", 0, 48)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setText("Registro de partidas");

        javax.swing.GroupLayout backgroundTittleLayout = new javax.swing.GroupLayout(backgroundTittle);
        backgroundTittle.setLayout(backgroundTittleLayout);
        backgroundTittleLayout.setHorizontalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundTittleLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        backgroundTittleLayout.setVerticalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundTittleLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        background.add(backgroundTittle);
        backgroundTittle.setBounds(100, 40, 900, 70);

        team1Background1.setBackground(new java.awt.Color(56, 56, 101));

        equipoTittle.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        equipoTittle.setForeground(new java.awt.Color(255, 255, 255));
        equipoTittle.setText("Equipo");

        equipo.setBackground(new java.awt.Color(128, 128, 168));
        equipo.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        equipo.setForeground(new java.awt.Color(255, 255, 255));
        equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fecha.setBackground(new java.awt.Color(128, 128, 168));
        fecha.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        rivalTittle.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        rivalTittle.setForeground(new java.awt.Color(255, 255, 255));
        rivalTittle.setText("rival");

        rival.setBackground(new java.awt.Color(128, 128, 168));
        rival.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        rival.setForeground(new java.awt.Color(255, 255, 255));
        rival.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rivalActionPerformed(evt);
            }
        });

        marcador.setBackground(new java.awt.Color(128, 128, 168));
        marcador.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        marcador.setForeground(new java.awt.Color(255, 255, 255));

        kills.setBackground(new java.awt.Color(128, 128, 168));
        kills.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        kills.setForeground(new java.awt.Color(255, 255, 255));

        deaths.setBackground(new java.awt.Color(128, 128, 168));
        deaths.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        deaths.setForeground(new java.awt.Color(255, 255, 255));

        assists.setBackground(new java.awt.Color(128, 128, 168));
        assists.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        assists.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout team1Background1Layout = new javax.swing.GroupLayout(team1Background1);
        team1Background1.setLayout(team1Background1Layout);
        team1Background1Layout.setHorizontalGroup(
            team1Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(team1Background1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(team1Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assists, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deaths, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kills, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(team1Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(equipoTittle)
                        .addComponent(rivalTittle)
                        .addComponent(fecha)
                        .addComponent(equipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rival, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marcador, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        team1Background1Layout.setVerticalGroup(
            team1Background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(team1Background1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(equipoTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rivalTittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rival, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(marcador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kills, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deaths, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(assists, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        background.add(team1Background1);
        team1Background1.setBounds(170, 190, 360, 430);
        background.add(jLabel1);
        jLabel1.setBounds(860, 300, 0, 0);

        team2Background.setBackground(new java.awt.Color(165, 88, 114));
        team2Background.setMinimumSize(new java.awt.Dimension(360, 470));

        equipo2Tittle.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        equipo2Tittle.setForeground(new java.awt.Color(255, 255, 255));
        equipo2Tittle.setText("Equipo");

        equipo2.setBackground(new java.awt.Color(182, 139, 154));
        equipo2.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        equipo2.setForeground(new java.awt.Color(255, 255, 255));
        equipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fecha2.setBackground(new java.awt.Color(182, 139, 154));
        fecha2.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        fecha2.setForeground(new java.awt.Color(255, 255, 255));
        fecha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecha2ActionPerformed(evt);
            }
        });

        rival2Tittle.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        rival2Tittle.setForeground(new java.awt.Color(255, 255, 255));
        rival2Tittle.setText("rival");

        rival2.setBackground(new java.awt.Color(182, 139, 154));
        rival2.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        rival2.setForeground(new java.awt.Color(255, 255, 255));
        rival2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        marcador2.setBackground(new java.awt.Color(182, 139, 154));
        marcador2.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        marcador2.setForeground(new java.awt.Color(255, 255, 255));

        kills2.setBackground(new java.awt.Color(182, 139, 154));
        kills2.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        kills2.setForeground(new java.awt.Color(255, 255, 255));


        deaths2.setBackground(new java.awt.Color(182, 139, 154));
        deaths2.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        deaths2.setForeground(new java.awt.Color(255, 255, 255));

        assists2.setBackground(new java.awt.Color(182, 139, 154));
        assists2.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        assists2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout team2BackgroundLayout = new javax.swing.GroupLayout(team2Background);
        team2Background.setLayout(team2BackgroundLayout);
        team2BackgroundLayout.setHorizontalGroup(
            team2BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(team2BackgroundLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(team2BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assists2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deaths2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kills2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(team2BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(equipo2Tittle)
                        .addComponent(rival2Tittle)
                        .addComponent(fecha2)
                        .addComponent(equipo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rival2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(marcador2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        team2BackgroundLayout.setVerticalGroup(
            team2BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(team2BackgroundLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(equipo2Tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rival2Tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rival2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(marcador2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kills2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deaths2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(assists2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        background.add(team2Background);
        team2Background.setBounds(570, 190, 350, 430);

        team1.setFont(new java.awt.Font("VALORANT", 0, 36)); // NOI18N
        team1.setForeground(new java.awt.Color(255, 255, 255));
        team1.setText("TEAM 1");
        background.add(team1);
        team1.setBounds(280, 140, 150, 50);

        team2.setFont(new java.awt.Font("VALORANT", 0, 36)); // NOI18N
        team2.setForeground(new java.awt.Color(255, 255, 255));
        team2.setText("TEAM 2");
        background.add(team2);
        team2.setBounds(670, 140, 150, 50);

        jButton1.setBackground(new java.awt.Color(117, 169, 169));
        jButton1.setFont(new java.awt.Font("VALORANT", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Registrar partida");
        background.add(jButton1);
        jButton1.setBounds(410, 650, 290, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 1082, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fecha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha2ActionPerformed

    private void rivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rivalActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    // Getters para acceder a los campos desde InterfazEsports
    public String getEquipo1() { return (String) equipo.getSelectedItem(); }
    public String getFecha1() { return fecha.getText(); }
    public String getRival1() { return (String) rival.getSelectedItem(); }
    public String getMarcador1() { return marcador.getText(); }
    public String getKills1() { return kills.getText(); }
    public String getDeaths1() { return deaths.getText(); }
    public String getAssists1() { return assists.getText(); }
 
    public String getEquipo2() { return (String) equipo2.getSelectedItem(); }
    public String getFecha2() { return fecha2.getText(); }
    public String getRival2() { return (String) rival2.getSelectedItem(); }
    public String getMarcador2() { return marcador2.getText(); }
    public String getKills2() { return kills2.getText(); }
    public String getDeaths2() { return deaths2.getText(); }
    public String getAssists2() { return assists2.getText(); }
  

    public void limpiarCampos() {
        fecha.setText("");
        marcador.setText("");
        kills.setText("");
        deaths.setText("");
        assists.setText("");

        fecha2.setText("");
        marcador2.setText("");
        kills2.setText("");
        deaths2.setText("");
        assists2.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assists;
    private javax.swing.JTextField assists2;
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundTittle;
    private javax.swing.JTextField deaths;
    private javax.swing.JTextField deaths2;
    private javax.swing.JComboBox<String> equipo;
    private javax.swing.JComboBox<String> equipo2;
    private javax.swing.JLabel equipo2Tittle;
    private javax.swing.JLabel equipoTittle;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField fecha2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kills;
    private javax.swing.JTextField kills2;
    private javax.swing.JTextField marcador;
    private javax.swing.JTextField marcador2;
    private javax.swing.JComboBox<String> rival;
    private javax.swing.JComboBox<String> rival2;
    private javax.swing.JLabel rival2Tittle;
    private javax.swing.JLabel rivalTittle;
    private javax.swing.JLabel team1;
    private javax.swing.JPanel team1Background1;
    private javax.swing.JLabel team2;
    private javax.swing.JPanel team2Background;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
