/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package umariana.cupi2.esports.interfaz;

import umariana.cupi2.esports.mundo.Esports;

/**
 *
 * @author Usuario
 */
public class PanelRegistroJugadores extends javax.swing.JPanel {
private InterfazEsports ventana;
private Esports esports;

    /**
     * Creates new form PanelRegistroJugadores
     */
public PanelRegistroJugadores(InterfazEsports ventana, Esports modelo) {
    this.ventana = ventana;
    this.esports = modelo;
    initComponents();
    cargarEquipos();
    registrarButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            registrarJugadorActionPerformed(evt);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sage = new javax.swing.JLabel();
        backgroundTittle = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        nombreCompletoTittle = new javax.swing.JLabel();
        nombreCompleto = new javax.swing.JTextField();
        nicknameTittle = new javax.swing.JLabel();
        nickname = new javax.swing.JTextField();
        correoTittle = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        equipoTittle = new javax.swing.JLabel();
        equipo = new javax.swing.JComboBox<>();
        kdaTittle = new javax.swing.JLabel();
        KDA = new javax.swing.JTextField();
        registrarButton = new javax.swing.JButton();
        sageSpray = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(25, 25, 50));
        background.setLayout(null);

        sage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umariana/cupi2/esports/interfaz/Sage.png"))); // NOI18N
        background.add(sage);
        sage.setBounds(410, 100, 790, 970);

        backgroundTittle.setBackground(new java.awt.Color(51, 51, 93));

        tittle.setFont(new java.awt.Font("Top Show", 0, 48)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setText("Registro de jugadores");

        javax.swing.GroupLayout backgroundTittleLayout = new javax.swing.GroupLayout(backgroundTittle);
        backgroundTittle.setLayout(backgroundTittleLayout);
        backgroundTittleLayout.setHorizontalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundTittleLayout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        backgroundTittleLayout.setVerticalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundTittleLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        background.add(backgroundTittle);
        backgroundTittle.setBounds(90, 40, 790, 70);

        nombreCompletoTittle.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        nombreCompletoTittle.setForeground(new java.awt.Color(255, 255, 255));
        nombreCompletoTittle.setText("Nombre Completo");
        background.add(nombreCompletoTittle);
        nombreCompletoTittle.setBounds(130, 150, 260, 21);

        nombreCompleto.setBackground(new java.awt.Color(83, 83, 91));
        nombreCompleto.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        nombreCompleto.setForeground(new java.awt.Color(255, 255, 255));
        background.add(nombreCompleto);
        nombreCompleto.setBounds(130, 170, 320, 50);

        nicknameTittle.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        nicknameTittle.setForeground(new java.awt.Color(255, 255, 255));
        nicknameTittle.setText("Nickname");
        background.add(nicknameTittle);
        nicknameTittle.setBounds(130, 230, 260, 21);

        nickname.setBackground(new java.awt.Color(83, 83, 91));
        nickname.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        nickname.setForeground(new java.awt.Color(255, 255, 255));
        nickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nicknameActionPerformed(evt);
            }
        });
        background.add(nickname);
        nickname.setBounds(130, 250, 320, 50);

        correoTittle.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        correoTittle.setForeground(new java.awt.Color(255, 255, 255));
        correoTittle.setText("Correo");
        background.add(correoTittle);
        correoTittle.setBounds(130, 310, 260, 21);

        correo.setBackground(new java.awt.Color(83, 83, 91));
        correo.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        correo.setForeground(new java.awt.Color(255, 255, 255));
        background.add(correo);
        correo.setBounds(130, 330, 320, 50);

        equipoTittle.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        equipoTittle.setForeground(new java.awt.Color(255, 255, 255));
        equipoTittle.setText("Selecciona tu Equipo");
        background.add(equipoTittle);
        equipoTittle.setBounds(130, 390, 260, 21);

        equipo.setBackground(new java.awt.Color(83, 83, 91));
        equipo.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        equipo.setForeground(new java.awt.Color(255, 255, 255));
        equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoActionPerformed(evt);
            }
        });
        background.add(equipo);
        equipo.setBounds(130, 410, 320, 50);

        kdaTittle.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        kdaTittle.setForeground(new java.awt.Color(255, 255, 255));
        kdaTittle.setText("KDA");
        background.add(kdaTittle);
        kdaTittle.setBounds(130, 470, 260, 21);

        KDA.setBackground(new java.awt.Color(83, 83, 91));
        KDA.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        KDA.setForeground(new java.awt.Color(255, 255, 255));
        KDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KDAActionPerformed(evt);
            }
        });
        background.add(KDA);
        KDA.setBounds(130, 490, 320, 50);

        registrarButton.setBackground(new java.awt.Color(133, 185, 203));
        registrarButton.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        registrarButton.setForeground(new java.awt.Color(36, 52, 84));
        registrarButton.setText("Registrar");
        background.add(registrarButton);
        registrarButton.setBounds(260, 580, 150, 50);

        sageSpray.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umariana/cupi2/esports/interfaz/sageSpray.png"))); // NOI18N
        background.add(sageSpray);
        sageSpray.setBounds(140, 550, 120, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameActionPerformed

    private void equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipoActionPerformed

    private void KDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KDAActionPerformed

    private void cargarEquipos() {
        equipo.removeAllItems();
        for (umariana.cupi2.esports.mundo.Equipo eq : esports.getEquipos()) {
            equipo.addItem(eq.getNombre());
        }
    }

    private void registrarJugadorActionPerformed(java.awt.event.ActionEvent evt) {
        String nombre = nombreCompleto.getText().trim();
        String nick = nickname.getText().trim();
        String email = correo.getText().trim();
        String equipoSeleccionado = (String) equipo.getSelectedItem();
        String kdaStr = KDA.getText().trim();

        try {
            if (nombre.isEmpty() || nick.isEmpty() || email.isEmpty() || equipoSeleccionado == null || kdaStr.isEmpty()) {
                throw new Exception("Todos los campos son obligatorios.");
            }

            String[] kdaParts = kdaStr.split("/");
            if (kdaParts.length != 3) {
                throw new Exception("KDA debe ser en formato K/D/A (ej: 5/4/3).");
            }

            int kills = Integer.parseInt(kdaParts[0].trim());
            int deaths = Integer.parseInt(kdaParts[1].trim());
            int assists = Integer.parseInt(kdaParts[2].trim());

            ventana.registrarJugador(nombre, nick, email, equipoSeleccionado, kills, deaths, assists);

            // Limpiar campos
            nombreCompleto.setText("");
            nickname.setText("");
            correo.setText("");
            KDA.setText("");
            equipo.setSelectedIndex(-1);

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "KDA debe contener números válidos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KDA;
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundTittle;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel correoTittle;
    private javax.swing.JComboBox<String> equipo;
    private javax.swing.JLabel equipoTittle;
    private javax.swing.JLabel kdaTittle;
    private javax.swing.JTextField nickname;
    private javax.swing.JLabel nicknameTittle;
    private javax.swing.JTextField nombreCompleto;
    private javax.swing.JLabel nombreCompletoTittle;
    private javax.swing.JButton registrarButton;
    private javax.swing.JLabel sage;
    private javax.swing.JLabel sageSpray;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
