/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package umariana.cupi2.esports.interfaz;

import umariana.cupi2.esports.mundo.Esports;

/**
 *
 * @author Usuario
 */
public class PanelConsultarJugadores extends javax.swing.JPanel {
private InterfazEsports ventana;
private Esports esports;
    /**
     * Creates new form PanelConsultarJugadores
     */
public PanelConsultarJugadores(InterfazEsports ventana, Esports modelo) {
    this.ventana = ventana;
    this.esports = modelo;
    initComponents();
    cargarEquipos();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        viper = new javax.swing.JLabel();
        backgroundTittle = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        equipoTittle = new javax.swing.JLabel();
        equipo = new javax.swing.JComboBox<>();
        verKDA = new javax.swing.JButton();
        verPromedioVictorias1 = new javax.swing.JButton();
        verPromedioDerrotas = new javax.swing.JButton();
        verJugadorMasKills = new javax.swing.JButton();
        listaBackgorund = new javax.swing.JPanel();
        lista = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList<>();

        background.setBackground(new java.awt.Color(27, 43, 43));
        background.setLayout(null);

        viper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/umariana/cupi2/esports/interfaz/viper.png"))); // NOI18N
        background.add(viper);
        viper.setBounds(140, 140, 320, 600);

        backgroundTittle.setBackground(new java.awt.Color(23, 75, 75));

        tittle.setFont(new java.awt.Font("Top Show", 0, 48)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setText("Consultar jugadores");

        javax.swing.GroupLayout backgroundTittleLayout = new javax.swing.GroupLayout(backgroundTittle);
        backgroundTittle.setLayout(backgroundTittleLayout);
        backgroundTittleLayout.setHorizontalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundTittleLayout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
        );
        backgroundTittleLayout.setVerticalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundTittleLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(tittle)
                .addContainerGap())
        );

        background.add(backgroundTittle);
        backgroundTittle.setBounds(90, 30, 810, 80);

        equipoTittle.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        equipoTittle.setForeground(new java.awt.Color(255, 255, 255));
        equipoTittle.setText("Selecciona el equipo");
        background.add(equipoTittle);
        equipoTittle.setBounds(490, 140, 260, 21);

        equipo.setBackground(new java.awt.Color(83, 83, 91));
        equipo.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        equipo.setForeground(new java.awt.Color(255, 255, 255));
        equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        background.add(equipo);
        equipo.setBounds(490, 160, 320, 50);

        verKDA.setBackground(new java.awt.Color(0, 102, 102));
        verKDA.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        verKDA.setForeground(new java.awt.Color(255, 255, 255));
        verKDA.setText("Ver KDA");
        verKDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verKDAActionPerformed(evt);
            }
        });
        background.add(verKDA);
        verKDA.setBounds(490, 220, 320, 40);

        verPromedioVictorias1.setBackground(new java.awt.Color(0, 102, 102));
        verPromedioVictorias1.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        verPromedioVictorias1.setForeground(new java.awt.Color(255, 255, 255));
        verPromedioVictorias1.setText("Ver Promedio Victorias");
        verPromedioVictorias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPromedioVictorias1ActionPerformed(evt);
            }
        });
        background.add(verPromedioVictorias1);
        verPromedioVictorias1.setBounds(490, 270, 320, 40);

        verPromedioDerrotas.setBackground(new java.awt.Color(0, 102, 102));
        verPromedioDerrotas.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        verPromedioDerrotas.setForeground(new java.awt.Color(255, 255, 255));
        verPromedioDerrotas.setText("Ver Promedio Derrotas");
        verPromedioDerrotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPromedioDerrotasActionPerformed(evt);
            }
        });
        background.add(verPromedioDerrotas);
        verPromedioDerrotas.setBounds(490, 320, 320, 40);

        verJugadorMasKills.setBackground(new java.awt.Color(0, 102, 102));
        verJugadorMasKills.setFont(new java.awt.Font("VALORANT", 0, 15)); // NOI18N
        verJugadorMasKills.setForeground(new java.awt.Color(255, 255, 255));
        verJugadorMasKills.setText("Ver Jugador Con Más Kills");
        verJugadorMasKills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verJugadorMasKillsActionPerformed(evt);
            }
        });
        background.add(verJugadorMasKills);
        verJugadorMasKills.setBounds(490, 370, 320, 40);

        listaBackgorund.setBackground(new java.awt.Color(34, 71, 71));

        listaJugadores.setBackground(new java.awt.Color(221, 221, 221));
        listaJugadores.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        listaJugadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista.setViewportView(listaJugadores);

        javax.swing.GroupLayout listaBackgorundLayout = new javax.swing.GroupLayout(listaBackgorund);
        listaBackgorund.setLayout(listaBackgorundLayout);
        listaBackgorundLayout.setHorizontalGroup(
            listaBackgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listaBackgorundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        listaBackgorundLayout.setVerticalGroup(
            listaBackgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listaBackgorundLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        background.add(listaBackgorund);
        listaBackgorund.setBounds(490, 440, 330, 220);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verKDAActionPerformed(java.awt.event.ActionEvent evt) {
        String equipoSeleccionado = (String) equipo.getSelectedItem();
        if (equipoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un equipo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        umariana.cupi2.esports.mundo.Equipo eq = esports.darEquipoPorNombre(equipoSeleccionado);
        if (eq == null || eq.getJugadores().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay jugadores en este equipo.", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String[] kdas = new String[eq.getJugadores().size()];
        for (int i = 0; i < eq.getJugadores().size(); i++) {
            umariana.cupi2.esports.mundo.Jugador j = eq.getJugadores().get(i);
            kdas[i] = j.getNickname() + " - KDA: " + String.format("%.2f", j.getKDA());
        }
        listaJugadores.setListData(kdas);
    }

    private void verPromedioDerrotasActionPerformed(java.awt.event.ActionEvent evt) {
        String equipoSeleccionado = (String) equipo.getSelectedItem();
        if (equipoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un equipo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        umariana.cupi2.esports.mundo.Equipo eq = esports.darEquipoPorNombre(equipoSeleccionado);
        double promedio = eq.promedioDerrotas();
        javax.swing.JOptionPane.showMessageDialog(this, "Promedio de derrotas: " + String.format("%.2f", promedio), "Resultado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void verJugadorMasKillsActionPerformed(java.awt.event.ActionEvent evt) {
        String equipoSeleccionado = (String) equipo.getSelectedItem();
        if (equipoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un equipo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        umariana.cupi2.esports.mundo.Equipo eq = esports.darEquipoPorNombre(equipoSeleccionado);
        if (eq == null || eq.getJugadores().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay jugadores en este equipo.", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        umariana.cupi2.esports.mundo.Jugador maxKills = null;
        for (umariana.cupi2.esports.mundo.Jugador j : eq.getJugadores()) {
            if (maxKills == null || j.getKills() > maxKills.getKills()) {
                maxKills = j;
            }
        }

        if (maxKills != null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Jugador con más kills: " + maxKills.getNickname() + " (" + maxKills.getKills() + " kills)", "Resultado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void verPromedioVictorias1ActionPerformed(java.awt.event.ActionEvent evt) {
        String equipoSeleccionado = (String) equipo.getSelectedItem();
        if (equipoSeleccionado == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecciona un equipo.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        umariana.cupi2.esports.mundo.Equipo eq = esports.darEquipoPorNombre(equipoSeleccionado);
        double promedio = eq.promedioVictorias();
        javax.swing.JOptionPane.showMessageDialog(this, "Promedio de victorias: " + String.format("%.2f", promedio), "Resultado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void cargarEquipos() {
        equipo.removeAllItems();
        for (umariana.cupi2.esports.mundo.Equipo eq : esports.getEquipos()) {
            equipo.addItem(eq.getNombre());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundTittle;
    private javax.swing.JComboBox<String> equipo;
    private javax.swing.JLabel equipoTittle;
    private javax.swing.JScrollPane lista;
    private javax.swing.JPanel listaBackgorund;
    private javax.swing.JList<String> listaJugadores;
    private javax.swing.JLabel tittle;
    private javax.swing.JButton verJugadorMasKills;
    private javax.swing.JButton verKDA;
    private javax.swing.JButton verPromedioDerrotas;
    private javax.swing.JButton verPromedioVictorias1;
    private javax.swing.JLabel viper;
    // End of variables declaration//GEN-END:variables
}
