/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package umariana.cupi2.esports.interfaz;

import umariana.cupi2.esports.mundo.Esports;

/**
 *
 * @author Usuario
 */
public class PanelConsultarJugadores extends javax.swing.JPanel {
private InterfazEsports ventana;
private Esports esports;
    /**
     * Creates new form PanelConsultarJugadores
     */
public PanelConsultarJugadores(InterfazEsports ventana, Esports modelo) {
    this.ventana = ventana;
    this.esports = modelo;
    initComponents();
    cargarEquipos();
    verKDA.addActionListener(e -> ventana.consultarKDA((String) equipo.getSelectedItem()));
    verPromedioVictorias.addActionListener(e -> ventana.consultarPromedioVictorias((String) equipo.getSelectedItem()));
    verPromedioDerrotas.addActionListener(e -> ventana.consultarPromedioDerrotas((String) equipo.getSelectedItem()));
    verJugadorMasKills1.addActionListener(e -> ventana.consultarJugadorMasKills((String) equipo.getSelectedItem()));
}

private void cargarEquipos() {
    equipo.removeAllItems();
    for (umariana.cupi2.esports.mundo.Equipo eq : esports.getEquipos()) {
        equipo.addItem(eq.getNombre());
    }
}

public void actualizarLista(String[] items) {
    listaJugadores.setListData(items);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        viper = new javax.swing.JLabel();
        backgroundTittle = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        equipoTittle = new javax.swing.JLabel();
        equipo = new javax.swing.JComboBox<>();
        verKDA = new javax.swing.JButton();
        verPromedioVictorias = new javax.swing.JButton();
        verPromedioDerrotas = new javax.swing.JButton();
        lista = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList<>();
        listaBackgorund = new javax.swing.JPanel();
        verJugadorMasKills1 = new javax.swing.JButton();

        background.setBackground(new java.awt.Color(27, 43, 43));
        background.setLayout(null);
        background.add(viper);
        viper.setBounds(0, 90, 370, 600);

        backgroundTittle.setBackground(new java.awt.Color(23, 75, 75));

        tittle.setFont(new java.awt.Font("Top Show", 0, 48)); // NOI18N
        tittle.setForeground(new java.awt.Color(255, 255, 255));
        tittle.setText("Consultar jugadores");

        javax.swing.GroupLayout backgroundTittleLayout = new javax.swing.GroupLayout(backgroundTittle);
        backgroundTittle.setLayout(backgroundTittleLayout);
        backgroundTittleLayout.setHorizontalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTittleLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(tittle, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        backgroundTittleLayout.setVerticalGroup(
            backgroundTittleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundTittleLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(tittle)
                .addContainerGap())
        );

        background.add(backgroundTittle);
        backgroundTittle.setBounds(40, 30, 630, 80);

        equipoTittle.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        equipoTittle.setForeground(new java.awt.Color(255, 255, 255));
        equipoTittle.setText("Selecciona el equipo");
        background.add(equipoTittle);
        equipoTittle.setBounds(330, 140, 260, 21);

        equipo.setBackground(new java.awt.Color(83, 83, 91));
        equipo.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        equipo.setForeground(new java.awt.Color(255, 255, 255));
        equipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        background.add(equipo);
        equipo.setBounds(330, 160, 320, 50);

        verKDA.setBackground(new java.awt.Color(0, 102, 102));
        verKDA.setFont(new java.awt.Font("VALORANT", 0, 18)); // NOI18N
        verKDA.setForeground(new java.awt.Color(255, 255, 255));
        verKDA.setText("Ver KDA");
        verKDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verKDAActionPerformed(evt);
            }
        });
        background.add(verKDA);
        verKDA.setBounds(350, 230, 270, 40);

        verPromedioVictorias.setBackground(new java.awt.Color(0, 102, 102));
        verPromedioVictorias.setFont(new java.awt.Font("VALORANT", 0, 16)); // NOI18N
        verPromedioVictorias.setForeground(new java.awt.Color(255, 255, 255));
        verPromedioVictorias.setText("ver promedio victorias");
        verPromedioVictorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPromedioVictoriasActionPerformed(evt);
            }
        });
        background.add(verPromedioVictorias);
        verPromedioVictorias.setBounds(350, 280, 270, 40);

        verPromedioDerrotas.setBackground(new java.awt.Color(0, 102, 102));
        verPromedioDerrotas.setFont(new java.awt.Font("VALORANT", 0, 15)); // NOI18N
        verPromedioDerrotas.setForeground(new java.awt.Color(255, 255, 255));
        verPromedioDerrotas.setText("ver promedio derrotas");
        verPromedioDerrotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPromedioDerrotasActionPerformed(evt);
            }
        });
        background.add(verPromedioDerrotas);
        verPromedioDerrotas.setBounds(350, 330, 270, 40);

        listaJugadores.setBackground(new java.awt.Color(221, 221, 221));
        listaJugadores.setFont(new java.awt.Font("VALORANT", 0, 14)); // NOI18N
        listaJugadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lista.setViewportView(listaJugadores);

        background.add(lista);
        lista.setBounds(340, 450, 290, 180);

        listaBackgorund.setBackground(new java.awt.Color(34, 71, 71));

        javax.swing.GroupLayout listaBackgorundLayout = new javax.swing.GroupLayout(listaBackgorund);
        listaBackgorund.setLayout(listaBackgorundLayout);
        listaBackgorundLayout.setHorizontalGroup(
            listaBackgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        listaBackgorundLayout.setVerticalGroup(
            listaBackgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        background.add(listaBackgorund);
        listaBackgorund.setBounds(320, 430, 330, 220);

        verJugadorMasKills1.setBackground(new java.awt.Color(0, 102, 102));
        verJugadorMasKills1.setFont(new java.awt.Font("VALORANT", 0, 15)); // NOI18N
        verJugadorMasKills1.setForeground(new java.awt.Color(255, 255, 255));
        verJugadorMasKills1.setText("ver jugador con mas kills");
        verJugadorMasKills1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verJugadorMasKills1ActionPerformed(evt);
            }
        });
        background.add(verJugadorMasKills1);
        verJugadorMasKills1.setBounds(350, 380, 270, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void verKDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verKDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verKDAActionPerformed

    private void verPromedioVictoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPromedioVictoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verPromedioVictoriasActionPerformed

    private void verPromedioDerrotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPromedioDerrotasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verPromedioDerrotasActionPerformed

    private void verJugadorMasKills1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verJugadorMasKills1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verJugadorMasKills1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundTittle;
    private javax.swing.JComboBox<String> equipo;
    private javax.swing.JLabel equipoTittle;
    private javax.swing.JScrollPane lista;
    private javax.swing.JPanel listaBackgorund;
    private javax.swing.JList<String> listaJugadores;
    private javax.swing.JLabel tittle;
    private javax.swing.JButton verJugadorMasKills1;
    private javax.swing.JButton verKDA;
    private javax.swing.JButton verPromedioDerrotas;
    private javax.swing.JButton verPromedioVictorias;
    private javax.swing.JLabel viper;
    // End of variables declaration//GEN-END:variables
}
